# Generated by Django 2.0.6 on 2018-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0014_auto_20180630_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-06-30 15:54:11.177286  Create diary'),
        ),
    ]
