# Generated by Django 2.0.3 on 2018-08-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0015_auto_20180824_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-08-24 19:01:19.951975  Create diary'),
        ),
    ]
