# Generated by Django 2.0.3 on 2018-08-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0015_auto_20180630_1554'),
        ('lenotes', '0016_auto_20180824_1901'),
    ]

    operations = [
    ]
