# Generated by Django 2.0.3 on 2018-08-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0018_auto_20180824_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-08-24 23:05:12.668872  Create diary'),
        ),
    ]
