# Generated by Django 2.0.3 on 2018-09-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='mention',
            field=models.CharField(default='', max_length=60),
        ),
    ]
