# Generated by Django 2.0.3 on 2018-08-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_embed', '0002_auto_20180824_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text_Embed',
        ),
    ]
